apiVersion: v1
kind: Secret
metadata:
  name: osrm-data-secret
  namespace: osrm
type: Opaque
stringData:
  DATA_URL: "https://seusite.com.br/osrm/osrm-data.tar.gz"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: osrm
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "TroqueEssaSenha123!"   # TROQUE ANTES DE SUBIR
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: osrm
type: Opaque
stringData:
  POSTGRES_DB: "keycloak"
  POSTGRES_USER: "keycloak"
  POSTGRES_PASSWORD: "TroqueEssaSenha456!"          # TROQUE ANTES DE SUBIR
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-secret
  namespace: osrm
type: Opaque
stringData:
  KONG_PG_DATABASE: "kong"
  KONG_PG_USER: "kong"
  KONG_PG_PASSWORD: "TroqueEssaSenha789!"           # TROQUE ANTES DE SUBIR
